---
apiVersion: helm.toolkit.fluxcd.io/v2beta1
kind: HelmRelease
metadata:
  name: influxdb
  namespace: flux-system
spec:
  chart:
    spec:
      chart: influxdb/1.1.9
      sourceRef:
        kind: HelmRepository
        name: bitnami
  interval: 5m0s
  releaseName: influxdb
  targetNamespace: default

